config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/wa_slider:
      branch: main
      repo: https://github.com/stevenjgibbons/wa_slider
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/wa_slider git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-orange-oyster.sh
        container: qc.acc_muggy-ruby-toad
  QC.Doc:
    repos:
      github.com/stevenjgibbons/wa_slider find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-olive-dachsbracke.sh
        container: qc.doc_squirrely-white-turtle
      github.com/stevenjgibbons/wa_slider git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-cerise-bison.sh
        container: qc.doc_freaky-cinnabar-beagle
      github.com/stevenjgibbons/wa_slider markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-cinnabar-jackal.sh
        container: qc.doc_cheeky-gold-vulture
  QC.Lic:
    repos:
      github.com/stevenjgibbons/wa_slider licensee:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-plum-tarsier.sh
        container: qc.lic_surly-red-donkey
  QC.Sec:
    repos:
      github.com/stevenjgibbons/wa_slider bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-platinum-terrier.sh
        container: qc.sec_breezy-ivory-antelope
  QC.Sty:
    repos:
      github.com/stevenjgibbons/wa_slider flake8:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-goldenrod-meerkat.sh
        container: qc.sty_woolly-cobalt-kiwi
  QC.Uni:
    repos:
      github.com/stevenjgibbons/wa_slider pytest:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-lemon-cassowary.sh
        container: qc.uni_lovely-red-tang
  QC.Ver:
    repos:
      github.com/stevenjgibbons/wa_slider get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-heliotrope-kangaroo.sh
        container: qc.ver_squeaky-purple-dalmatian
timeout: 5400
