config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/wa_slider:
      branch: main
      repo: https://github.com/stevenjgibbons/wa_slider
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/wa_slider git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-russet-devil.sh
        container: qc.acc_droopy-bistre-squid
  QC.Doc:
    repos:
      github.com/stevenjgibbons/wa_slider find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-olivine-foxhound.sh
        container: qc.doc_slaphappy-gold-anteater
      github.com/stevenjgibbons/wa_slider git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-tan-starfish.sh
        container: qc.doc_crappy-chartreuse-tamarin
      github.com/stevenjgibbons/wa_slider markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-brass-deer.sh
        container: qc.doc_muggy-puce-dormouse
  QC.Lic:
    repos:
      github.com/stevenjgibbons/wa_slider licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-cinnabar-binturong.sh
        container: qc.lic_sloppy-platinum-beaver
  QC.Sec:
    repos:
      github.com/stevenjgibbons/wa_slider bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-corn-squirrel.sh
        container: qc.sec_stinky-viridian-gorilla
  QC.Sty:
    repos:
      github.com/stevenjgibbons/wa_slider flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-olivine-llama.sh
        container: qc.sty_clammy-saffron-angora
  QC.Uni:
    repos:
      github.com/stevenjgibbons/wa_slider pytest:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-corn-starfish.sh
        container: qc.uni_leaky-cornflower-ibis
  QC.Ver:
    repos:
      github.com/stevenjgibbons/wa_slider get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-charcoal-lemming.sh
        container: qc.ver_muggy-azure-yak
timeout: 5400
